// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

const String API_KEY = String.fromEnvironment('API_KEY');

class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: API_KEY,
    appId: '1:1074623424963:web:3e31c8d2254e8ef83df576',
    messagingSenderId: '1074623424963',
    projectId: 'poem-app-2c3c7',
    authDomain: 'poem-app-2c3c7.firebaseapp.com',
    storageBucket: 'poem-app-2c3c7.appspot.com',
    measurementId: 'G-F4R04PZR7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: API_KEY,
    appId: '1:1074623424963:android:f3ca65ef515ad0f23df576',
    messagingSenderId: '1074623424963',
    projectId: 'poem-app-2c3c7',
    storageBucket: 'poem-app-2c3c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: API_KEY,
    appId: '1:1074623424963:ios:c2f10d60317c5e303df576',
    messagingSenderId: '1074623424963',
    projectId: 'poem-app-2c3c7',
    storageBucket: 'poem-app-2c3c7.appspot.com',
    iosBundleId: 'com.example.poemApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: API_KEY,
    appId: '1:1074623424963:ios:c2f10d60317c5e303df576',
    messagingSenderId: '1074623424963',
    projectId: 'poem-app-2c3c7',
    storageBucket: 'poem-app-2c3c7.appspot.com',
    iosBundleId: 'com.example.poemApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: API_KEY,
    appId: '1:1074623424963:web:56216d99e01a13e13df576',
    messagingSenderId: '1074623424963',
    projectId: 'poem-app-2c3c7',
    authDomain: 'poem-app-2c3c7.firebaseapp.com',
    storageBucket: 'poem-app-2c3c7.appspot.com',
    measurementId: 'G-34SYNV78XR',
  );

}